apiVersion: apps/v1
kind: Deployment
metadata:
  name: castor
  labels:
    app: castor
    monitor: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: castor
  template:
    metadata:
      labels:
        app: castor
        monitor: 'true'
    spec:
      containers:
      - name: castor
        image: pangealab/castor:latest
        ports:
        - containerPort: 8080
        env:
          - name: LS_ACCESS_TOKEN
            value: "${{ secrets.LIGHTSTEP_ACCESS_TOKEN }}"
          - name: LS_SERVICE_NAME
            value: castor
          - name: LS_SERVICE_VERSION
            value: latest
---
apiVersion: v1
kind: Service
metadata:
  name: castor
  labels:
    app: erebus
    monitor: 'true'
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: castor          
